name: FunctionalTests

on: [push]

jobs:
  run-functional-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11      
      - name: prepareFunctionalTests
        run: |
          ./gradlew prepareFunctionalTests
      - name: buildProtocolLanguage
        run: |
          cd functional_tests
          ../gradlew buildProtocolLanguage
      - name: execute_functional_tests
        run: |
          cd functional_tests
          pip install -r requirements.txt
          sh execute_functional_tests.sh
      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: server_log_*.txt          
