name: Lint

on: [push]

jobs:
  lintFunctionalTests:

    runs-on: ubuntu-latest

    steps:    
    - name: Run linter
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        cd functional_tests
        flake8 mpsserverfunctests
