name: Lint

on: [push]

jobs:
  lintFunctionalTests:

    runs-on: ubuntu-latest

    steps:  
    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0
        working_directory: ./functional_tests
        args: install        
    - name: Run linter
      run: |
        cd functional_tests
        flake8 mpsserverfunctests
