name: Lint

on: [push]

jobs:
  lintFunctionalTests:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - uses: actions/checkout@v1      
    # - name: Install
    #   uses: abatilo/actions-poetry@v1.5.0
    #   with:
    #     python_version: 3.7.0
    #     poetry_version: 1.0
    #     working_directory: ./functional_tests
    #     args: install        
    - name: Run linter
      run: |
        cd functional_tests
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        poetry install
        pip install flake8
        python -m flake8 mpsserverfunctests mpsserverfunctests
